- text: "basic"
  nodes:
    - text: "home"
      url: "/"
    - text: "about"
      url: "/about"
- text: "posts"
  nodes:
    - text: "index_posts"
      url: "/posts"
    - text: "new_post"
      url: "/posts/new"
- text: "users"
  nodes:
    - text: "index_users"
      url: "/users"
- text: "members"
  nodes:
    - text: "google_apps"
      url: "/auth/google_apps"
      logged_out: true
    - text: "twitter"
      url: "/auth/twitter"
      logged_out: true
    - text: "signout"
      url: "/signout"
      logged_in: true
